var json_Titik_Hidden_Gem_Bali_1 = {
"type": "FeatureCollection",
"name": "Titik_Hidden_Gem_Bali_1",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "OID_": "0", "Name": "Warung Krishna", "FolderPath": "rute sanur\/Directions from Warung Krishna, Sanur Kauh, Denpasar City, Bali to Parisi French Cuisine, Jalan Batur Sari, Sanur Kauh, Denpasar City, Bali", "SymbolID": "0", "AltMode": -1.0, "Base": 0.0, "Snippet": null, "PopupInfo": null, "HasLabel": -1.0, "LabelID": "0" }, "geometry": { "type": "Point", "coordinates": [ 115.253442600000085, -8.698844799999961 ] } },
{ "type": "Feature", "properties": { "OID_": "0", "Name": "KooD", "FolderPath": "rute sanur\/Directions from Warung Krishna, Sanur Kauh, Denpasar City, Bali to Parisi French Cuisine, Jalan Batur Sari, Sanur Kauh, Denpasar City, Bali", "SymbolID": "1", "AltMode": -1.0, "Base": 0.0, "Snippet": null, "PopupInfo": null, "HasLabel": -1.0, "LabelID": "0" }, "geometry": { "type": "Point", "coordinates": [ 115.253762, -8.698664299999962 ] } },
{ "type": "Feature", "properties": { "OID_": "0", "Name": "Museum Le Mayeur", "FolderPath": "rute sanur\/Directions from Warung Krishna, Sanur Kauh, Denpasar City, Bali to Parisi French Cuisine, Jalan Batur Sari, Sanur Kauh, Denpasar City, Bali", "SymbolID": "2", "AltMode": -1.0, "Base": 0.0, "Snippet": null, "PopupInfo": null, "HasLabel": -1.0, "LabelID": "0" }, "geometry": { "type": "Point", "coordinates": [ 115.263705800000025, -8.674799899999925 ] } },
{ "type": "Feature", "properties": { "OID_": "0", "Name": "Pantai Sanur", "FolderPath": "rute sanur\/Directions from Warung Krishna, Sanur Kauh, Denpasar City, Bali to Parisi French Cuisine, Jalan Batur Sari, Sanur Kauh, Denpasar City, Bali", "SymbolID": "3", "AltMode": -1.0, "Base": 0.0, "Snippet": null, "PopupInfo": null, "HasLabel": -1.0, "LabelID": "0" }, "geometry": { "type": "Point", "coordinates": [ 115.26327480000009, -8.673709199999962 ] } },
{ "type": "Feature", "properties": { "OID_": "0", "Name": "Jogging Track Prapat Beris", "FolderPath": "rute sanur\/Directions from Warung Krishna, Sanur Kauh, Denpasar City, Bali to Parisi French Cuisine, Jalan Batur Sari, Sanur Kauh, Denpasar City, Bali", "SymbolID": "4", "AltMode": -1.0, "Base": 0.0, "Snippet": null, "PopupInfo": null, "HasLabel": -1.0, "LabelID": "0" }, "geometry": { "type": "Point", "coordinates": [ 115.252690800000096, -8.693819899999937 ] } },
{ "type": "Feature", "properties": { "OID_": "0", "Name": "Paris'i French Cuisine", "FolderPath": "rute sanur\/Directions from Warung Krishna, Sanur Kauh, Denpasar City, Bali to Parisi French Cuisine, Jalan Batur Sari, Sanur Kauh, Denpasar City, Bali", "SymbolID": "5", "AltMode": -1.0, "Base": 0.0, "Snippet": null, "PopupInfo": null, "HasLabel": -1.0, "LabelID": "0" }, "geometry": { "type": "Point", "coordinates": [ 115.252975700000093, -8.693818 ] } }
]
}
